### ISSUE TITLE
Release/Tag v1.0.0

### ISSUE THREAD

**Issue by vladimiroff** [bwmarrin/snowflake#16]
A few months ago Go 1.11 has been released with the concept of modules which allows to fetch a release by tag of the format `vX.Y.Z` (e.g. `v1.0.0`). Years before that projects like glide and dep also rely on tags to determine version and ensure safe updates without breaking API changes.

The project status since last year says:

> This package should be considered stable and completed. Any additions in the future will strongly avoid API changes to existing functions. Please see issues for any remaining TODO items that are planned.

There are no any TODO items left and since there are no planned API changes I propose to introduce a `v1.0.0` tag.

**Comment by bwmarrin** [comment]
Good idea, I'll look into this soon.

**Comment by bwmarrin** [comment]
It's been awhile :( but I finally got time to tend to my projects here.

Turns out, there are some TODOs left before a 1.0 release.  However, I've added two tags.
v0.0.0 is the state the library was in when you made this comment
v0.1.0 is where it's at currently after a few changes.

1.0.0 will come after I deprecate a few global variables and solve the monotonic clock issue. 

Thanks.
