### ISSUE TITLE
Alternative to ID.Time()?

### ISSUE THREAD

**Issue by muscache** [bwmarrin/snowflake#35]
`ID.Time()` is a deprecated method. What should I use instead?
Thanks

**Comment by codemedic** [comment]
In PR #33 I have removed `ID.Time()`.

Assuming that #33 will be approved and merged and if this functionality is absolutely necessary, it should be provided via a method on `Node` since we need the configuration of the node to decode the ID.

```
t, n, s, err := node.DecomposeID(id)
```

Where `t` would give you the time with milliseconds precision, `n` would be node number and `s` would be step value. If the node number does not match that of `node` or if step is out of range then `err` will be set appropriately.

**Comment by bwmarrin** [comment]
@muscache 

That deprecation notice was added a long time ago when I thought I'd have time to build it's replacement shortly after - but that didn't happen.  Currently there is no replacement for ID.Time() and you can continue to use it.  Furthermore, once a replacement is accepted I won't remove the old methods for at least several months (if not longer).
